-- ─────────────────────────────────────────────────────────────
-- KYRO — 0005: attribution plumbing
--
-- Closes the gap between docs (the "tracking token" the attribution model
-- describes) and the schema (which had nowhere to put one). The token is the
-- single value that ties a Shopify order back to one creator's video:
--
--   submission.tracking_token
--     → appended to the ad's destination URL as utm_content
--     → Shopify records it on the customer's visit
--     → read back from order.customerJourneySummary
--     → matched here
--
-- Also gives `orders` somewhere to keep the UTM values we matched on, so an
-- attribution can be audited or disputed later without re-querying Shopify.
--
-- Run AFTER 0004_platform_credentials.sql. Idempotent.
-- ─────────────────────────────────────────────────────────────

-- ── Tracking token on submissions ────────────────────────────
-- 16 hex characters. Opaque, unguessable, short enough to sit in a URL
-- without drawing attention. Generated by the database so no code path can
-- forget to set one.
alter table public.submissions
  add column if not exists tracking_token text not null default encode(gen_random_bytes(8), 'hex');

create unique index if not exists submissions_tracking_token_idx
  on public.submissions(tracking_token);

comment on column public.submissions.tracking_token is
  'Opaque id carried in the ad URL as utm_content and read back from Shopify''s customer journey. The join key for attribution. Never reuse or reissue: doing so re-points historical orders at a different creator.';

-- ── What we matched on, kept for audit ───────────────────────
alter table public.orders add column if not exists utm_source   text;
alter table public.orders add column if not exists utm_medium   text;
alter table public.orders add column if not exists utm_campaign text;
alter table public.orders add column if not exists utm_content  text;
alter table public.orders add column if not exists utm_term     text;

-- Why an order ended up attributed, or why it did not. Free text, written by
-- the webhook receiver. Makes "this order should have been mine" answerable.
alter table public.orders add column if not exists attribution_note text;

-- Set when we have asked Shopify for the customer journey and got an answer,
-- successful or not. Distinguishes "no journey data" from "never looked".
alter table public.orders add column if not exists journey_checked_at timestamptz;

create index if not exists orders_utm_content_idx on public.orders(utm_content)
  where utm_content is not null;

create index if not exists orders_unattributed_idx on public.orders(brand_id, placed_at)
  where journey_checked_at is null;

-- ── Webhook delivery bookkeeping ─────────────────────────────
-- Shopify retries a failed delivery up to 8 times over ~48h. Counting the
-- attempts tells us the difference between a blip and something genuinely
-- broken.
alter table public.webhook_events add column if not exists attempts integer not null default 0;

comment on column public.webhook_events.attempts is
  'Incremented on each delivery of the same X-Shopify-Webhook-Id. More than 1 means an earlier attempt failed and Shopify retried.';
